# Generated by Django 4.1 on 2024-02-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
