# Generated by Django 4.1 on 2024-02-19 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_shoppingitem_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingitem',
            options={'ordering': ('name', 'description', 'quantity', 'is_completed', 'created_on', 'updated_on')},
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
